Prepare frzr for local media deployments

diff --git a/__frzr-deploy b/__frzr-deploy
--- a/__frzr-deploy
+++ b/__frzr-deploy
@@ -160,54 +160,63 @@ main() {
 	if [ -e "${MOUNT_PATH}/source" ]; then
 		SOURCE=`cat "${MOUNT_PATH}/source" | head -1`
 	else
-		echo "ERROR: no source specified"
-		exit 1
+		echo "WARNING: source wasn't specified"
 	fi
+	
+	if [  ${local_install} == true ]; then
 
-	REPO=$(echo "${SOURCE}" | cut -f 1 -d ':')
-	CHANNEL=$(echo "${SOURCE}" | cut -f 2 -d ':')
-
-	RELEASES_URL="https://api.github.com/repos/${REPO}/releases"
-
-	IMG_URL=$(curl --http1.1 -L -s "${RELEASES_URL}" | get_img_url "${CHANNEL}")
-
-	if [ -z "$IMG_URL" ] || [ "$IMG_URL" == "null" ]; then
-		echo "No matching source found"
-		if curl --http1.1 -L -s "${RELEASES_URL}" | grep "rate limit" > /dev/null; then
-			echo "GitHub API rate limit exceeded"
-			exit 29
-		fi
-		exit 1
-	fi
-
-	FILE_NAME=$(basename ${IMG_URL})
-	NAME=$(echo "${FILE_NAME}" | cut -f 1 -d '.')
-	BASE_URL=$(dirname "${IMG_URL}")
-	CHECKSUM=$(curl --http1.1 -L -s "${BASE_URL}/sha256sum.txt" | cut -f -1 -d ' ')
-	SUBVOL="${DEPLOY_PATH}/${NAME}"
-	IMG_FILE="${MOUNT_PATH}/${FILE_NAME}"
-
-	if [ -e ${SUBVOL} ]; then
-		echo "${NAME} already installed; aborting"
-		exit
-	fi
-
-	if [ -z ${SHOW_UI} ]; then
-		echo "downloading ${NAME}..."
-		curl --http1.1 -L -o "${IMG_FILE}" -C - "${IMG_URL}"
+	mkdir tmp_source
+	mount -o rw -L CHIMERA_UPDATE /root/tmp_source
+		FILE_NAME=$(basename /root/tmp_source/*.img.tar.xz*)	
+		NAME=$(echo "${FILE_NAME}" | cut -f 1 -d '.')
+		SUBVOL="${DEPLOY_PATH}/${NAME}"
+		IMG_FILE="/root/tmp_source/${FILE_NAME}"
 	else
-		curl --http1.1 -# -L -o "${IMG_FILE}" -C - "${IMG_URL}" 2>&1 | \
-		stdbuf -oL tr '\r' '\n' | grep --line-buffered -oP '[0-9]*+(?=.[0-9])' | grep --line-buffered -v '100' | \
-		whiptail --gauge "Downloading system image (${NAME})" 10 50 0
-	fi
+		REPO=$(echo "${SOURCE}" | cut -f 1 -d ':')
+		CHANNEL=$(echo "${SOURCE}" | cut -f 2 -d ':')
 
-	CHECKSUM2=`sha256sum "${IMG_FILE}" | cut -d' ' -f 1`
-	if [ "$CHECKSUM" != "$CHECKSUM2" ]; then
-		rm -f "${IMG_FILE}"
-		echo "checksum does not match; aborting"
-		exit 1
-	fi
+		RELEASES_URL="https://api.github.com/repos/${REPO}/releases"
 
+		IMG_URL=$(curl --http1.1 -L -s "${RELEASES_URL}" | get_img_url "${CHANNEL}")
+
+		if [ -z "$IMG_URL" ] || [ "$IMG_URL" == "null" ]; then
+			echo "No matching source found"
+			if curl --http1.1 -L -s "${RELEASES_URL}" | grep "rate limit" > /dev/null; then
+				echo "GitHub API rate limit exceeded"
+				exit 29
+			fi
+			exit 1
+		fi
+
+		FILE_NAME=$(basename ${IMG_URL})
+		NAME=$(echo "${FILE_NAME}" | cut -f 1 -d '.')
+		BASE_URL=$(dirname "${IMG_URL}")
+		CHECKSUM=$(curl --http1.1 -L -s "${BASE_URL}/sha256sum.txt" | cut -f -1 -d ' ')
+		SUBVOL="${DEPLOY_PATH}/${NAME}"
+		IMG_FILE="${MOUNT_PATH}/${FILE_NAME}"
+
+		if [ -e ${SUBVOL} ]; then
+			echo "${NAME} already installed; aborting"
+			exit
+		fi
+	
+		if [ -z ${SHOW_UI} ]; then
+			echo "downloading ${NAME}..."
+			curl --http1.1 -L -o "${IMG_FILE}" -C - "${IMG_URL}"
+		else
+			curl --http1.1 -# -L -o "${IMG_FILE}" -C - "${IMG_URL}" 2>&1 | \
+			stdbuf -oL tr '\r' '\n' | grep --line-buffered -oP '[0-9]*+(?=.[0-9])' | grep --line-buffered -v '100' | \
+			whiptail --gauge "Downloading system image (${NAME})" 10 50 0
+		fi
+
+		CHECKSUM2=`sha256sum "${IMG_FILE}" | cut -d' ' -f 1`
+		if [ "$CHECKSUM" != "$CHECKSUM2" ]; then
+			rm -f "${IMG_FILE}"
+			echo "checksum does not match; aborting"
+			exit 1
+		fi
+	fi
+	
 	if [ -z ${SHOW_UI} ]; then
 		echo "installing ${NAME}..."
 	else
