Clean up whitespaces

diff --git a/__frzr-deploy b/__frzr-deploy
--- a/__frzr-deploy
+++ b/__frzr-deploy
@@ -4,9 +4,9 @@ set -e
 set -o pipefail
 
 get_img_url() {
-    CHANNEL=$1
+	CHANNEL=$1
 
-    result=$(jq '[
+	result=$(jq '[
           sort_by(.created_at) |
           reverse |
           .[] |
@@ -15,15 +15,15 @@ get_img_url() {
           select(.state=="uploaded")
         ]')
 
-    if [ "$CHANNEL" == "testing" ]; then
-        result=$(echo $result | jq '[ .[] | select(.name|test("UNSTABLE")|not) ]')
-    elif [ "$CHANNEL" == "stable" ]; then
-        result=$(echo $result | jq '[ .[] | select(.prerelease==false) ]')
-    elif [ "$CHANNEL" != "unstable" ]; then
-        result=$(echo $result | jq "[ .[] | select(.url|contains(\"-${CHANNEL}_\")) ]")
-    fi
+	if [ "$CHANNEL" == "testing" ]; then
+		result=$(echo $result | jq '[ .[] | select(.name|test("UNSTABLE")|not) ]')
+	elif [ "$CHANNEL" == "stable" ]; then
+		result=$(echo $result | jq '[ .[] | select(.prerelease==false) ]')
+	elif [ "$CHANNEL" != "unstable" ]; then
+		result=$(echo $result | jq "[ .[] | select(.url|contains(\"-${CHANNEL}_\")) ]")
+	fi
 
-    echo $result | jq 'first | .url' | sed 's/"//g'
+	echo $result | jq 'first | .url' | sed 's/"//g'
 }
 
 get_syslinux_dir() {
@@ -62,7 +62,7 @@ get_syslinux_cfg() {
 	local additional_initrd=${3}
 	local additional_arguments=${4}
 
-echo "default ${version}
+	echo "default ${version}
 label ${version}
 kernel ${prefix}/${version}/vmlinuz-linux
 append root=LABEL=frzr_root rw rootflags=subvol=deployments/${version} quiet splash loglevel=3 rd.systemd.show_status=auto rd.udev.log_priority=3 ${additional_arguments}
@@ -75,7 +75,7 @@ get_deployment_to_delete() {
 	local syslinux_cfg_path=${2}
 	local deployment_path=${3}
 
-	local TO_BOOT=`get_next_boot_deployment ${current_version} ${syslinux_cfg_path}`
+	local TO_BOOT=$(get_next_boot_deployment ${current_version} ${syslinux_cfg_path})
 	ls -1 ${deployment_path} | grep -v ${current_version} | grep -v ${TO_BOOT} | head -1 || echo
 }
 
@@ -84,8 +84,8 @@ get_next_boot_deployment() {
 	local syslinux_cfg_path=${2}
 
 	local TO_BOOT='this-is-not-a-valid-version-string'
-	if [ -f "${syslinux_cfg_path}" ] && grep "^default" "${syslinux_cfg_path}" > /dev/null; then
-		TO_BOOT=`grep ^default ${syslinux_cfg_path} | sed 's/default //'`
+	if [ -f "${syslinux_cfg_path}" ] && grep "^default" "${syslinux_cfg_path}" >/dev/null; then
+		TO_BOOT=$(grep ^default ${syslinux_cfg_path} | sed 's/default //')
 	fi
 
 	echo ${TO_BOOT}
@@ -96,14 +96,13 @@ clean_progress() {
 	local postfix=$2
 	local last_value=$scale
 	while IFS= read -r line; do
-		value=$(( ${line}*${scale}/100 ))
+		value=$((${line} * ${scale} / 100))
 		if [ "$last_value" != "$value" ]; then
 			echo ${value}${postfix}
 			last_value=$value
 		fi
 	done
 }
-
 
 main() {
 	if [ $EUID -ne 0 ]; then
@@ -116,24 +115,24 @@ main() {
 	FRZR_SOURCE=""
 	FRZR_PARAMS=""
 
-	while (( "$#" )); do
+	while (("$#")); do
 		case $1 in
-			--check)
-				FRZR_CHECK_UPDATE=1
-				shift
-				;;
-			--steam-progress)
-				FRZR_STEAM_PROGRESS=1
-				shift
-				;;
-			-*|--*)
-				echo "Unknown argument $1"
-				exit 1
-				;;
-			*) # preserve positional arguments
-				FRZR_PARAMS="$FRZR_PARAMS $1"
-				shift
-				;;
+		--check)
+			FRZR_CHECK_UPDATE=1
+			shift
+			;;
+		--steam-progress)
+			FRZR_STEAM_PROGRESS=1
+			shift
+			;;
+		-* | --*)
+			echo "Unknown argument $1"
+			exit 1
+			;;
+		*) # preserve positional arguments
+			FRZR_PARAMS="$FRZR_PARAMS $1"
+			shift
+			;;
 		esac
 	done
 
@@ -152,7 +151,7 @@ main() {
 		sleep 5
 	fi
 
-	if ! mountpoint -q ${MOUNT_PATH}/boot && ls -1 /dev/disk/by-label | grep frzr_efi > /dev/null; then
+	if ! mountpoint -q ${MOUNT_PATH}/boot && ls -1 /dev/disk/by-label | grep frzr_efi >/dev/null; then
 		mkdir -p ${MOUNT_PATH}/boot
 		mount -L frzr_efi ${MOUNT_PATH}/boot
 		sleep 5
@@ -175,9 +174,9 @@ main() {
 	# - we are currently running inside a frzr deployment (i.e. not during install)
 	# - the deployment is not currently running
 	# - the deployment is not configured to be run on next boot
-	if frzr-release > /dev/null; then
-		CURRENT=`frzr-release`
-		TO_DELETE=`get_deployment_to_delete ${CURRENT} ${BOOT_CFG} ${DEPLOY_PATH}`
+	if frzr-release >/dev/null; then
+		CURRENT=$(frzr-release)
+		TO_DELETE=$(get_deployment_to_delete ${CURRENT} ${BOOT_CFG} ${DEPLOY_PATH})
 
 		if [ ! -z ${TO_DELETE} ]; then
 			echo "deleting ${TO_DELETE}..."
@@ -187,20 +186,20 @@ main() {
 	fi
 
 	if [ ! -z $FRZR_SOURCE ] && [ $FRZR_CHECK_UPDATE -eq 0 ] && [ $FRZR_STEAM_PROGRESS -eq 0 ]; then
-		echo "$FRZR_SOURCE" > "${MOUNT_PATH}/source"
+		echo "$FRZR_SOURCE" >"${MOUNT_PATH}/source"
 	fi
 
 	if [ -e "${MOUNT_PATH}/source" ]; then
-		SOURCE=`cat "${MOUNT_PATH}/source" | head -1`
+		SOURCE=$(cat "${MOUNT_PATH}/source" | head -1)
 	else
 		echo "WARNING: source wasn't specified"
 	fi
-	
-	if [  ${local_install} ]; then
 
-	        mkdir tmp_source
-	        mount -o rw -L CHIMERA_UPDATE /root/tmp_source
-		FILE_NAME=$(basename /root/tmp_source/*.img.tar.xz*)	
+	if [ ${local_install} ]; then
+
+		mkdir tmp_source
+		mount -o rw -L CHIMERA_UPDATE /root/tmp_source
+		FILE_NAME=$(basename /root/tmp_source/*.img.tar.xz*)
 		NAME=$(echo "${FILE_NAME}" | cut -f 1 -d '.')
 		SUBVOL="${DEPLOY_PATH}/${NAME}"
 		IMG_FILE="/root/tmp_source/${FILE_NAME}"
@@ -214,7 +213,7 @@ main() {
 
 		if [ -z "$IMG_URL" ] || [ "$IMG_URL" == "null" ]; then
 			echo "No matching source found"
-			if curl --http1.1 -L -s "${RELEASES_URL}" | grep "rate limit" > /dev/null; then
+			if curl --http1.1 -L -s "${RELEASES_URL}" | grep "rate limit" >/dev/null; then
 				echo "GitHub API rate limit exceeded"
 				exit 29
 			fi
@@ -227,80 +226,79 @@ main() {
 		CHECKSUM=$(curl --http1.1 -L -s "${BASE_URL}/sha256sum.txt" | cut -f -1 -d ' ')
 		SUBVOL="${DEPLOY_PATH}/${NAME}"
 		IMG_FILE="${MOUNT_PATH}/${FILE_NAME}"
-		
-	        if [ -e ${SUBVOL} ]; then
-		        echo "${NAME} already installed; aborting"
-		        exit 7 # let Steam know there is no update available
-	        fi
 
-	        if [ $FRZR_CHECK_UPDATE -eq 1 ]; then
-		        echo "Update available: ${NAME}"
-		        exit 0 # let Steam know there is an update available
-	        fi
+		if [ -e ${SUBVOL} ]; then
+			echo "${NAME} already installed; aborting"
+			exit 7 # let Steam know there is no update available
+		fi
 
-	        if [ $FRZR_STEAM_PROGRESS -eq 1 ]; then
-		        curl --http1.1 -# -L -o "${IMG_FILE}" -C - "${IMG_URL}" 2>&1 | \
-		        stdbuf -oL tr '\r' '\n' | grep --line-buffered -oP '[0-9]*+(?=.[0-9])' | clean_progress 91 %
-	        elif [ -z ${SHOW_UI} ]; then
-		        echo "downloading ${NAME}..."
-		        curl --http1.1 -L -o "${IMG_FILE}" -C - "${IMG_URL}"
-	        else
-		        curl --http1.1 -# -L -o "${IMG_FILE}" -C - "${IMG_URL}" 2>&1 | \
-		        stdbuf -oL tr '\r' '\n' | grep --line-buffered -oP '[0-9]*+(?=.[0-9])' | clean_progress 100 | \
-		        whiptail --gauge "Downloading system image (${NAME})" 10 50 0
-	        fi
+		if [ $FRZR_CHECK_UPDATE -eq 1 ]; then
+			echo "Update available: ${NAME}"
+			exit 0 # let Steam know there is an update available
+		fi
 
-		        CHECKSUM2=`sha256sum "${IMG_FILE}" | cut -d' ' -f 1`
-		        if [ "$CHECKSUM" != "$CHECKSUM2" ]; then
-			        rm -f "${IMG_FILE}"
-			        echo "checksum does not match; aborting"
-			        exit 1
-		        fi
-		        
-        fi
-        
+		if [ $FRZR_STEAM_PROGRESS -eq 1 ]; then
+			curl --http1.1 -# -L -o "${IMG_FILE}" -C - "${IMG_URL}" 2>&1 |
+			stdbuf -oL tr '\r' '\n' | grep --line-buffered -oP '[0-9]*+(?=.[0-9])' | clean_progress 91 %
+		elif [ -z ${SHOW_UI} ]; then
+			echo "downloading ${NAME}..."
+			curl --http1.1 -L -o "${IMG_FILE}" -C - "${IMG_URL}"
+		else
+			curl --http1.1 -# -L -o "${IMG_FILE}" -C - "${IMG_URL}" 2>&1 |
+			stdbuf -oL tr '\r' '\n' | grep --line-buffered -oP '[0-9]*+(?=.[0-9])' | clean_progress 100 |
+			whiptail --gauge "Downloading system image (${NAME})" 10 50 0
+		fi
+
+		CHECKSUM2=$(sha256sum "${IMG_FILE}" | cut -d' ' -f 1)
+		if [ "$CHECKSUM" != "$CHECKSUM2" ]; then
+			rm -f "${IMG_FILE}"
+			echo "checksum does not match; aborting"
+			exit 1
+		fi
+
+	fi
+
 	if [ -z ${SHOW_UI} ]; then
-	        echo "installing ${NAME}..."
-        else
-	        whiptail --infobox "Extracting and installing system image (${NAME}). This may take some time." 10 50
-        fi
-        
-        tar xfO ${IMG_FILE} | btrfs receive --quiet ${DEPLOY_PATH}
-        mkdir -p ${MOUNT_PATH}/boot/${NAME}
-        cp ${SUBVOL}/boot/vmlinuz-linux ${MOUNT_PATH}/boot/${NAME}
-        cp ${SUBVOL}/boot/initramfs-linux.img ${MOUNT_PATH}/boot/${NAME}
+		echo "installing ${NAME}..."
+	else
+		whiptail --infobox "Extracting and installing system image (${NAME}). This may take some time." 10 50
+	fi
 
-        ADDITIONAL_INITRD=""
-        if [ -e ${SUBVOL}/boot/amd-ucode.img ] ; then
-	        cp ${SUBVOL}/boot/amd-ucode.img ${MOUNT_PATH}/boot/${NAME}
-	        ADDITIONAL_INITRD="${ADDITIONAL_INITRD}${PREFIX}/${NAME}/amd-ucode.img,"
-        fi
-        if [ -e ${SUBVOL}/boot/intel-ucode.img ] ; then
-	        cp ${SUBVOL}/boot/intel-ucode.img ${MOUNT_PATH}/boot/${NAME}
-	        ADDITIONAL_INITRD="${ADDITIONAL_INITRD}${PREFIX}/${NAME}/intel-ucode.img,"
-        fi
+	tar xfO ${IMG_FILE} | btrfs receive --quiet ${DEPLOY_PATH}
+	mkdir -p ${MOUNT_PATH}/boot/${NAME}
+	cp ${SUBVOL}/boot/vmlinuz-linux ${MOUNT_PATH}/boot/${NAME}
+	cp ${SUBVOL}/boot/initramfs-linux.img ${MOUNT_PATH}/boot/${NAME}
 
-        ADDITIONAL_ARGUMENTS=""
-        if [ -e ${SUBVOL}/usr/lib/frzr.d/bootconfig.conf ] ; then
-	        ADDITIONAL_ARGUMENTS="$ADDITIONAL_ARGUMENTS $(cat ${SUBVOL}/usr/lib/frzr.d/bootconfig.conf)"
-        fi
+	ADDITIONAL_INITRD=""
+	if [ -e ${SUBVOL}/boot/amd-ucode.img ]; then
+		cp ${SUBVOL}/boot/amd-ucode.img ${MOUNT_PATH}/boot/${NAME}
+		ADDITIONAL_INITRD="${ADDITIONAL_INITRD}${PREFIX}/${NAME}/amd-ucode.img,"
+	fi
+	if [ -e ${SUBVOL}/boot/intel-ucode.img ]; then
+		cp ${SUBVOL}/boot/intel-ucode.img ${MOUNT_PATH}/boot/${NAME}
+		ADDITIONAL_INITRD="${ADDITIONAL_INITRD}${PREFIX}/${NAME}/intel-ucode.img,"
+	fi
 
-        get_syslinux_cfg ${NAME} ${PREFIX} ${ADDITIONAL_INITRD} ${ADDITIONAL_ARGUMENTS} > ${BOOT_CFG}
+	ADDITIONAL_ARGUMENTS=""
+	if [ -e ${SUBVOL}/usr/lib/frzr.d/bootconfig.conf ]; then
+		ADDITIONAL_ARGUMENTS="$ADDITIONAL_ARGUMENTS $(cat ${SUBVOL}/usr/lib/frzr.d/bootconfig.conf)"
+	fi
 
-        rm -f ${MOUNT_PATH}/*.img.*
+	get_syslinux_cfg ${NAME} ${PREFIX} ${ADDITIONAL_INITRD} ${ADDITIONAL_ARGUMENTS} >${BOOT_CFG}
 
-        rm -rf /var/lib/pacman # undo frzr-unlock
+	rm -f ${MOUNT_PATH}/*.img.*
 
-        echo "deployment complete; restart to boot into ${NAME}"
+	rm -rf /var/lib/pacman # undo frzr-unlock
 
-        if command -v frzr-postupdate-script > /dev/null; then
-	        frzr-postupdate-script
-        fi
+	echo "deployment complete; restart to boot into ${NAME}"
+
+	if command -v frzr-postupdate-script >/dev/null; then
+		frzr-postupdate-script
+	fi
 
 	umount -R ${MOUNT_PATH}
 }
 
-
-if [ "$0" = "$BASH_SOURCE" ] ; then
+if [ "$0" = "$BASH_SOURCE" ]; then
 	main "$#"
 fi
