more whitespace fixes

diff --git a/__frzr-deploy b/__frzr-deploy
--- a/__frzr-deploy
+++ b/__frzr-deploy
@@ -197,7 +197,6 @@ main() {
 	fi
 	
 	if [  ${local_install} ]; then
-
 	        mkdir tmp_source
 	        mount -o rw -L CHIMERA_UPDATE /root/tmp_source
 		FILE_NAME=$(basename /root/tmp_source/*.img.tar.xz*)	
@@ -228,41 +227,40 @@ main() {
 		SUBVOL="${DEPLOY_PATH}/${NAME}"
 		IMG_FILE="${MOUNT_PATH}/${FILE_NAME}"
 		
-	        if [ -e ${SUBVOL} ]; then
-		        echo "${NAME} already installed; aborting"
-		        exit 7 # let Steam know there is no update available
-	        fi
+		if [ -e ${SUBVOL} ]; then
+			echo "${NAME} already installed; aborting"
+			exit 7 # let Steam know there is no update available
+		fi
 
-	        if [ $FRZR_CHECK_UPDATE -eq 1 ]; then
-		        echo "Update available: ${NAME}"
-		        exit 0 # let Steam know there is an update available
-	        fi
+		if [ $FRZR_CHECK_UPDATE -eq 1 ]; then
+			echo "Update available: ${NAME}"
+			exit 0 # let Steam know there is an update available
+		fi
 
-	        if [ $FRZR_STEAM_PROGRESS -eq 1 ]; then
-		        curl --http1.1 -# -L -o "${IMG_FILE}" -C - "${IMG_URL}" 2>&1 | \
-		        stdbuf -oL tr '\r' '\n' | grep --line-buffered -oP '[0-9]*+(?=.[0-9])' | clean_progress 91 %
-	        elif [ -z ${SHOW_UI} ]; then
-		        echo "downloading ${NAME}..."
-		        curl --http1.1 -L -o "${IMG_FILE}" -C - "${IMG_URL}"
-	        else
-		        curl --http1.1 -# -L -o "${IMG_FILE}" -C - "${IMG_URL}" 2>&1 | \
-		        stdbuf -oL tr '\r' '\n' | grep --line-buffered -oP '[0-9]*+(?=.[0-9])' | clean_progress 100 | \
-		        whiptail --gauge "Downloading system image (${NAME})" 10 50 0
-	        fi
+		if [ $FRZR_STEAM_PROGRESS -eq 1 ]; then
+			curl --http1.1 -# -L -o "${IMG_FILE}" -C - "${IMG_URL}" 2>&1 | \
+			stdbuf -oL tr '\r' '\n' | grep --line-buffered -oP '[0-9]*+(?=.[0-9])' | clean_progress 91 %
+		elif [ -z ${SHOW_UI} ]; then
+			echo "downloading ${NAME}..."
+			curl --http1.1 -L -o "${IMG_FILE}" -C - "${IMG_URL}"
+		else
+			curl --http1.1 -# -L -o "${IMG_FILE}" -C - "${IMG_URL}" 2>&1 | \
+			stdbuf -oL tr '\r' '\n' | grep --line-buffered -oP '[0-9]*+(?=.[0-9])' | clean_progress 100 | \
+			whiptail --gauge "Downloading system image (${NAME})" 10 50 0
+		fi
 
-		        CHECKSUM2=`sha256sum "${IMG_FILE}" | cut -d' ' -f 1`
-		        if [ "$CHECKSUM" != "$CHECKSUM2" ]; then
-			        rm -f "${IMG_FILE}"
-			        echo "checksum does not match; aborting"
-			        exit 1
-		        fi
-		        
+		CHECKSUM2=`sha256sum "${IMG_FILE}" | cut -d' ' -f 1`
+		if [ "$CHECKSUM" != "$CHECKSUM2" ]; then
+			rm -f "${IMG_FILE}"
+			echo "checksum does not match; aborting"
+			exit 1
+		fi
         fi
 
 	if [ -z ${SHOW_UI} ]; then
-	        echo "installing ${NAME}..."
+		echo "installing ${NAME}..."
 	else
-	        whiptail --infobox "Extracting and installing system image (${NAME}). This may take some time." 10 50
+		whiptail --infobox "Extracting and installing system image (${NAME}). This may take some time." 10 50
 	fi
 
 	tar xfO ${IMG_FILE} | btrfs receive --quiet ${DEPLOY_PATH}
@@ -272,17 +270,17 @@ main() {
 
 	ADDITIONAL_INITRD=""
 	if [ -e ${SUBVOL}/boot/amd-ucode.img ] ; then
-	        cp ${SUBVOL}/boot/amd-ucode.img ${MOUNT_PATH}/boot/${NAME}
-	        ADDITIONAL_INITRD="${ADDITIONAL_INITRD}${PREFIX}/${NAME}/amd-ucode.img,"
+		cp ${SUBVOL}/boot/amd-ucode.img ${MOUNT_PATH}/boot/${NAME}
+		ADDITIONAL_INITRD="${ADDITIONAL_INITRD}${PREFIX}/${NAME}/amd-ucode.img,"
 	fi
 	if [ -e ${SUBVOL}/boot/intel-ucode.img ] ; then
-	        cp ${SUBVOL}/boot/intel-ucode.img ${MOUNT_PATH}/boot/${NAME}
-	        ADDITIONAL_INITRD="${ADDITIONAL_INITRD}${PREFIX}/${NAME}/intel-ucode.img,"
+		cp ${SUBVOL}/boot/intel-ucode.img ${MOUNT_PATH}/boot/${NAME}
+		ADDITIONAL_INITRD="${ADDITIONAL_INITRD}${PREFIX}/${NAME}/intel-ucode.img,"
 	fi
 
 	ADDITIONAL_ARGUMENTS=""
 	if [ -e ${SUBVOL}/usr/lib/frzr.d/bootconfig.conf ] ; then
-	        ADDITIONAL_ARGUMENTS="$ADDITIONAL_ARGUMENTS $(cat ${SUBVOL}/usr/lib/frzr.d/bootconfig.conf)"
+		ADDITIONAL_ARGUMENTS="$ADDITIONAL_ARGUMENTS $(cat ${SUBVOL}/usr/lib/frzr.d/bootconfig.conf)"
 	fi
 
 	get_syslinux_cfg ${NAME} ${PREFIX} ${ADDITIONAL_INITRD} ${ADDITIONAL_ARGUMENTS} > ${BOOT_CFG}
@@ -294,7 +292,7 @@ main() {
 	echo "deployment complete; restart to boot into ${NAME}"
 
 	if command -v frzr-postupdate-script > /dev/null; then
-	        frzr-postupdate-script
+		frzr-postupdate-script
 	fi
 
 	umount -R ${MOUNT_PATH}
